@echo off
echo [92m[robloxstudio-rpc][0m Installing plugin...
copy src\plugin.lua %LOCALAPPDATA%\Roblox\Plugins\robloxstudio-rpc.lua /y
echo [92m[robloxstudio-rpc][0m Installing dependencies...
npm install